---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false
  - name: windows-8
    driver:
      box: roboticcheese/windows-8

suites:
  - name: default
    run_list:
      - recipe[plex-home-theater]
    attributes:
  - name: enable_and_start
    run_list:
      - recipe[plex-home-theater_test::enable_and_start]
    attributes:
    excludes:
      - macosx-travis
  - name: uninstall
    run_list:
      - recipe[plex-home-theater_test::uninstall]
    attributes:
